### ISSUE TITLE
Error when loading the module

### ISSUE THREAD

**Issue by enrcor01** [JamesRandall/AngularJS-OAuth2#7]
Hi, 

I am trying to use the plug-in as specified in the post, and I am getting an error when trying to load the module. Any idea why it could be?  

This is the error trace:

Error: [$injector:modulerr] http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=n...)
    at Error (native)
    at http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:6:416
    at http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:38:15
    at n (http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:7:322)
    at g (http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:37:92)
    at http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:37:261
    at n (http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:7:322)
    at g (http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:37:92)
    at db (http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:40:367)
    at d (http://localhost:8000/assets/libs/bower_components/angular/angular.min.js:19:219

**Comment by enrcor01** [comment]
My mistake.... I was loading "ngStorage" module instead of "ngstorage".  Both exists, but it seems that the second one is the one in use :)

**Comment by JamesRandall** [comment]
Hurrah - I like issues where I don't have to do anything!

Thanks for taking the time for letting me know what was going on - useful to know.

**Comment by simo3o** [comment]
Hi I'm having the same issue with loading the module, and I'm using "ngStorage", but I cannot find "ngstorage" enrcor01  says.
